* Python
** Lists
- the mathematical equivalent of a one dimensional list is a vector

- we crate a list of objects by enclosing the objects in square brackets (i.e.,[]). to reference a particular element of the list, we use the name of the list with the subscript of the element.

  the list indices begin at 0 and increment from left to right.

  #+begin_example py
  # the list element using their index
  # d[0] d[1] d[2]
  d = [3.5, 4.0, 9.34]
  print(d)    # prints [3.5, 4.0, 9.34]
  print(d[0]) # prints 3.5

  d[1] = 99
  print(d)    # prints [3.5, 99, 9.34]
  #+end_example

- lists can consist of objects of different types:
  integers, strings, floating-point numbers, other lists, and so forth.

#+begin_src python :results output
data = [3, 17.9, "a string", [9, 8, 7]]

i = 0   # we can use variable for the list
        # index as long as it is of type int

# len(data) returns the number of elements
while i < len(data):
    print("data[{}] is {}".format(i, data[i]))
    i += 1
#+end_src

#+RESULTS:
: data[0] is 3
: data[1] is 17.9
: data[2] is a string
: data[3] is [9, 8, 7]

we can easily iterate through a list using a for loop.
this program has the same output as the previous program

#+begin_src python :results output
data = [3, 17.9, "a string", [9, 8, 7]]

index = 0   # needed to print the index number, not
            # get element from the list


for val in data :
    print("data[{}] is {}".format(index, val))
    index += 1
#+end_src

#+RESULTS:
: data[0] is 3
: data[1] is 17.9
: data[2] is a string
: data[3] is [9, 8, 7]

which should you use ? when you don't care about the list indices, then the =for= loop is probably used more often. the =while= loop is more beneficial when the index of the list element is needed for something.

- here is how to use a list to find the max of numbers
  #+begin_src python :results output
  d = [8, 23, 99, 8]
  myMax = d[0]

  for val in d :
      if val > myMax :
          myMax = val

  print("the max is %d" % myMax)
  #+end_src

  #+RESULTS:
  : the max is 99

let's write a function to find min and max in a list
#+begin_src python :results output
def min_and_max( d ) :
    my_min = d[0]
    my_max = d[0]

    for x in d :
        if x < my_min :
            my_min = x
        if x > my_max :
            my_max = x

    return my_min, my_max

a = [23, -5, 0, 61]
b = [-9, 14, 55, -13, 99, 123, 72]

myMin, myMax = min_and_max(a)
print("min = %d, max = %d" % (myMin, myMax))

myMin, myMax = min_and_max(b)
print("min = %d, max = %d" % (myMin, myMax))
#+end_src

#+RESULTS:
: min = -5, max = 61
: min = -13, max = 123

but in python we have built in functions for this
#+begin_src python :results output
a = [23, -5, 0, 61]
b = [-9, 14, 55, -13, 99, 123, 72]

print(min(a))
print(max(a))
print(sum(a))
print()
print(min(b))
print(max(b))
print(sum(b))

#+end_src

#+RESULTS:
: -5
: 61
: 79
: 
: -13
: 123
: 341

- we have already seen that we can access list elements using their subscripts, with the subscripts starting at 0 and incrementing from left to right.

  we can also access the elements using subscripts that began with -1 and decrement from right to left

  [18, 73, 21, 52]  list
  -----------------------
   0   1   2   3    index from left
  -4  -3  -2  -1    index from right

- we can also slice a list to get a range of values:

  #+begin_src python :results output
  #indices   0   1   2   3   4   5   6   7
  oldList = [10, 20, 30, 40, 50, 60, 70, 80]

  #slice is [start_index : end_index : step size]
  #  step size is optional; defaults to 1
  # begins at start_index and keep going while less than end_index

  newList_1 = oldList[0:4:3]
  print(newList_1)
  newList_2 = oldList[2:5]
  print(newList_2)
  newList_3 = oldList[-1: :-2]
  print(newList_3)
  #+end_src

  #+RESULTS:
  : [10, 40]
  : [30, 40, 50]
  : [80, 60, 40, 20]

  leaving out one or both of the end indices allows us to get all values in a spacific direction:

  #+begin_src python :results output
  d = [23, 44, 19, 5, 61, 7]
  print(d[2:]) #start at index 2

  x = d[ : ] # copy list
  print(x)
  #+end_src

  #+RESULTS:
  : [19, 5, 61, 7]
  : [23, 44, 19, 5, 61, 7]

> *list methods*
some useful methods (think of a method as a function for a spacific type of object) for lists are:

*.* append(x) - adds x to end of list
*.* insert(i, x)- inserts x at index i
*.* pop() - remove last element from list
*.* sort() - sorts the list in ascending order(by default)
*.* reverse() - reverses the order of the list

- we use the method by connecting it to the last name with a period, for example,

  d = [1, 13, -24]
  d.append( 7 )
  print(d) # prints [1, 13, -24, 7]

> *Lists of Lists*
when accessing an element of a list within a list, we need to know which element of which list.

#+begin_src python :results output
data = [ [1, 2, 3], [4, 5, 6, 7, 8] ]

print(data[0][1])   # list 0, element 1
print(data[1][3])   # list 1, element 3
print(data[1][1:4])   # list 1, element 1 to 3

#+end_src

#+RESULTS:
: 2
: 7
: [5, 6, 7]

we can have lists within lists within lists....

> *Lists - indexing error*
*Warning* : A common error when accessing lists via subscripts is to use an index value that is too large.

#+begin_src python :results output
data = [3.5, 4, 9.34]  #contains 3 elements

#range(0, 4) produces the values 0 to 3
for i in range(0, 4) :
    print(data[i])
#+end_src

#+RESULTS:
: 3.5
: 4
: 9.34
: Traceback (most recent call last):
:  File "<stdin>", line 5, in <module>
: IndexError: list index out of range

> *Copying Lists*
There are times in which we wish to make changes to a list but need to know what the original list was. therefore, we want to make a copy of the list. the most obvious way to do this turns out not to do what we want.

#+begin_src python :results output
oldList = [1, 2, 3, 4, 5]
newList = oldList  # seems like the thing to do
print(oldList)  # prints [1, 2, 3, 4, 5]
print(newList)  # prints [1, 2, 3, 4, 5]

newList[3] = 99
print(oldList)  # prints [1, 2, 3, 99, 5]
print(newList)  # prints [1, 2, 3, 99, 5]

#+end_src
what happend?
-when we write
    newList = oldList

 we are creating what is called a 'shallow' copy. that is, =oldList= and =newList= both refer to the same list, so either name can be used to change the list.

 so how can we make a true copy, known as a deep copy of the list?

 Here are three options, but there are more.

 #+begin_src python :results output
 a = [1, 2, 3, 4]

 b = a[ : ] # slice all of the old list
 c = a.copy()
 d = list(a)  #can also be used with some non-list
              # objects to produce a list from them

 a[0] = 99

 print(a)  # prints [99, 2, 3, 4]
 print(b)  # prints [1, 2, 3, 4]
 print(c)  # prints [1, 2, 3, 4]
 print(d)  # prints [1, 2, 3, 4]

 #+end_src

 #+RESULTS:
 : [99, 2, 3, 4]
 : [1, 2, 3, 4]
 : [1, 2, 3, 4]
 : [1, 2, 3, 4]

> *List Comprehensions*
what if we need to use one list to make another list?
Example, we wish to add 5 to each element of a list, saving as a new list:

#+begin_src python :results output
d = [10, 20, 30, 40]

#loop version
a = [ ] #create empty list
for val in d :
    a.append(val + 5)

print(d)
print(a)

# list comprehensions version
b = [ val + 5 for val in d]
print(b) 
#+end_src

#+RESULTS:
: [10, 20, 30, 40]
: [15, 25, 35, 45]
: [15, 25, 35, 45]

what if we need to choose value based upon some condition being true?

#+begin_src python :results output
d = [2, 6, 3, 14, 12, 25]

### choose values that are multiples of 3

# loop version
a = [ ] # create empty list
for val in d :
    if val%3 == 0 :
        a.append(val)
print(a)

# list comprehensions version
b = [ val for val in d if val%3 == 0 ]
print(b)
#+end_src

#+RESULTS:
: [6, 3, 12]
: [6, 3, 12]

*** list application
 *Simulating a Perfect Shuffle*
**** Background
I once attended a presentation by an amateur magician in which he stated that performing 8 perfect shuffles in a row on a deck of 52 cards returned the deck to the original order. A perfect shuffle is where you divide the deck into two, evenly sized stacks and when merging the stacks you are able to do so such that every other card comes from the same stack.
**** Problem
Write a program to determine if 8 perfect shuffles in a row return a deck of 52 cards to the original order. I assume that you understand statements, conditionals, loops, lists, and functions. Below I create two versions of the program. The first is very explicit and doesn’t take advantage of many Python features.
**** Design
I start by thinking how to represent the cards. The claim above simply states that for whatever order the deck of cards is initially in, after 8 perfect shuffles it will return to its original order. It says nothing about the suits and values of the cards, so we don’t need to keep track of this information. Therefore, I will use an list consisting of the integers 1 to 52 as my cards. In the discussion below, this list is “cards”.

Each time I shuffle, I need to simulate dividing the deck into two stacks of 26 cards each followed by merging them such that one card comes from each stack during the merging. That is, when merging I get the first card from stack #1, the first card from stack #2, the second card from stack #1, the second card from stack #2, and so forth.

Representing the two smaller stacks is simple–the “left” stack will consist of the first 26 cards from the deck and the “right” stack will consist of the last 26 cards. That is
left[0] = cards[0]
left[1] = cards[1]
    .
    .
    .
left[25] = cards[25]

with a pattern of
left[i]= cards[i]

For producing the “right” stack, we can see that
right[0] = cards[26]
right[1] = cards[27]
    .
    .
    .
right[25] = cards[51]

with a pattern of
right[i] = cards[i + 26]

Merging is more of a challenge. I will print the current state of the loop after each shuffle and don’t care about the order before that, so I can re-use “cards” when merging. As for the merged values, cards[0] = left[0], cards[1] = right[0], cards[2] = left[1], cards[3] – right[1], and so forth. I can see that the indices of “cards” increments by one each time, but I use “left” and right” in pairs with the same index. That is, I use left[0] and right[0], then left[1] and right[1], and so on. This means that I need one indexing variable for “cards” and another for “left” and “right” so that I can increment them by different step sizes (for this approach).
**** Final Program, version 1:

#+begin_src python :results output
def shuffle( c ) :
    left  = [ ]
    right = [ ] 
 
    for i in range(0, 26) :
        left.append(c[i])
        right.append(c[i+26])
 
    i = 0
    k = 0
    while i < 52 :
        c[i]   = left[k]
        c[i+1] = right[k]
        i += 2
        k += 1
 
 
########  main  ########
cards = []
 
for i in range(0, 52) :
    cards.append(i+1)
 
print("original deck")
print(cards)
 
for i in range(0, 8) :
    shuffle(cards)
    print("\nshuffle # %d" % (i+1))
    print(cards)
#+end_src

#+RESULTS:
#+begin_example
original deck
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

shuffle # 1
[1, 27, 2, 28, 3, 29, 4, 30, 5, 31, 6, 32, 7, 33, 8, 34, 9, 35, 10, 36, 11, 37, 12, 38, 13, 39, 14, 40, 15, 41, 16, 42, 17, 43, 18, 44, 19, 45, 20, 46, 21, 47, 22, 48, 23, 49, 24, 50, 25, 51, 26, 52]

shuffle # 2
[1, 14, 27, 40, 2, 15, 28, 41, 3, 16, 29, 42, 4, 17, 30, 43, 5, 18, 31, 44, 6, 19, 32, 45, 7, 20, 33, 46, 8, 21, 34, 47, 9, 22, 35, 48, 10, 23, 36, 49, 11, 24, 37, 50, 12, 25, 38, 51, 13, 26, 39, 52]

shuffle # 3
[1, 33, 14, 46, 27, 8, 40, 21, 2, 34, 15, 47, 28, 9, 41, 22, 3, 35, 16, 48, 29, 10, 42, 23, 4, 36, 17, 49, 30, 11, 43, 24, 5, 37, 18, 50, 31, 12, 44, 25, 6, 38, 19, 51, 32, 13, 45, 26, 7, 39, 20, 52]

shuffle # 4
[1, 17, 33, 49, 14, 30, 46, 11, 27, 43, 8, 24, 40, 5, 21, 37, 2, 18, 34, 50, 15, 31, 47, 12, 28, 44, 9, 25, 41, 6, 22, 38, 3, 19, 35, 51, 16, 32, 48, 13, 29, 45, 10, 26, 42, 7, 23, 39, 4, 20, 36, 52]

shuffle # 5
[1, 9, 17, 25, 33, 41, 49, 6, 14, 22, 30, 38, 46, 3, 11, 19, 27, 35, 43, 51, 8, 16, 24, 32, 40, 48, 5, 13, 21, 29, 37, 45, 2, 10, 18, 26, 34, 42, 50, 7, 15, 23, 31, 39, 47, 4, 12, 20, 28, 36, 44, 52]

shuffle # 6
[1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]

shuffle # 7
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]

shuffle # 8
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]
#+end_example
**** Final Program, Version 2:
The design given above lends itself more to the first implementation, which is how you might do it in some other programming languages. However, we may wish to take advantage of Python’s language features that make some things easier. I can use slicing to produce the two subsets of the deck, resulting in two new lists.

When merging I can use slicing again, both on the left and right sides of the assignment operator. This includes using a step size other than 1. When merging, I want to make the following changes to “cards”: cards[0] = left[0], cards[2] = left[1], cards[4] = left[2], and so forth. Similar changes need to be made to “cards” at indices 1, 3, 5, … This can be performed with slicing.

#+begin_src python :results output
def shuffle( c ) :
    left  = c[  :26]  # slice from beginning to index 25
    right = c[26:  ]  # slice from index 26 to end
 
    c[0: :2] = left[ : ]   # replace every other value of
                           #   c starting at index 0
    c[1: :2] = right[ : ]  # replace every other value of
                           #   c starting at index 1
 
########  main  ########
# create list using list comprehension
cards = [ n for n in range(1, 52+1) ]
 
print("original deck")
print(cards)
 
for i in range(0, 8) :
    shuffle(cards)
    print("\nshuffle # %d" % (i+1))
    print(cards)
#+end_src

#+RESULTS:
#+begin_example
original deck
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

shuffle # 1
[1, 27, 2, 28, 3, 29, 4, 30, 5, 31, 6, 32, 7, 33, 8, 34, 9, 35, 10, 36, 11, 37, 12, 38, 13, 39, 14, 40, 15, 41, 16, 42, 17, 43, 18, 44, 19, 45, 20, 46, 21, 47, 22, 48, 23, 49, 24, 50, 25, 51, 26, 52]

shuffle # 2
[1, 14, 27, 40, 2, 15, 28, 41, 3, 16, 29, 42, 4, 17, 30, 43, 5, 18, 31, 44, 6, 19, 32, 45, 7, 20, 33, 46, 8, 21, 34, 47, 9, 22, 35, 48, 10, 23, 36, 49, 11, 24, 37, 50, 12, 25, 38, 51, 13, 26, 39, 52]

shuffle # 3
[1, 33, 14, 46, 27, 8, 40, 21, 2, 34, 15, 47, 28, 9, 41, 22, 3, 35, 16, 48, 29, 10, 42, 23, 4, 36, 17, 49, 30, 11, 43, 24, 5, 37, 18, 50, 31, 12, 44, 25, 6, 38, 19, 51, 32, 13, 45, 26, 7, 39, 20, 52]

shuffle # 4
[1, 17, 33, 49, 14, 30, 46, 11, 27, 43, 8, 24, 40, 5, 21, 37, 2, 18, 34, 50, 15, 31, 47, 12, 28, 44, 9, 25, 41, 6, 22, 38, 3, 19, 35, 51, 16, 32, 48, 13, 29, 45, 10, 26, 42, 7, 23, 39, 4, 20, 36, 52]

shuffle # 5
[1, 9, 17, 25, 33, 41, 49, 6, 14, 22, 30, 38, 46, 3, 11, 19, 27, 35, 43, 51, 8, 16, 24, 32, 40, 48, 5, 13, 21, 29, 37, 45, 2, 10, 18, 26, 34, 42, 50, 7, 15, 23, 31, 39, 47, 4, 12, 20, 28, 36, 44, 52]

shuffle # 6
[1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]

shuffle # 7
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]

shuffle # 8
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]
#+end_example
** Strings

